apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
stringData:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "incantogamus"
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "root"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  JWT_SECRET: "SvT4hmSMy3GptPScYx3ZCxvYJVrfKuc3"
  JWT_ACCESS_EXPIRATION_MINUTES: "1440"