const logger = require('../config/logger');
const Game = require('../models/game.model');

const games = [
  {
    name: 'The Elder Scrolls V: Skyrim',
    description: 'Skyrim is an open-world action RPG developed by Bethesda Game Studios.',
    releaseDate: '2011-11-11',
    genre: 'Action RPG',
    publisher: 'Bethesda Softworks',
  },
  {
    name: 'Red Dead Redemption 2',
    description: 'Red Dead Redemption 2 is an action-adventure game developed by Rockstar Games.',
    releaseDate: '2018-10-26',
    genre: 'Action-Adventure',
    publisher: 'Rockstar Games',
  },
  {
    name: 'Dark Souls III',
    description: 'Dark Souls III is an action RPG known for its challenging gameplay and dark fantasy setting.',
    releaseDate: '2016-04-12',
    genre: 'Action RPG',
    publisher: 'Bandai Namco Entertainment',
  },
  {
    name: 'Minecraft',
    description: 'Minecraft is a sandbox game that allows players to build and explore virtual worlds.',
    releaseDate: '2011-11-18',
    genre: 'Sandbox',
    publisher: 'Mojang Studios',
  },
  {
    name: 'Fortnite',
    description: 'Fortnite is a popular battle royale game developed by Epic Games.',
    releaseDate: '2017-07-25',
    genre: 'Battle Royale',
    publisher: 'Epic Games',
  },
  {
    name: 'Cyberpunk 2077',
    description: 'Cyberpunk 2077 is an open-world action RPG set in a dystopian future.',
    releaseDate: '2020-12-10',
    genre: 'Action RPG',
    publisher: 'CD Projekt',
  },
  {
    name: 'The Last of Us Part II',
    description: 'The Last of Us Part II is an action-adventure game developed by Naughty Dog.',
    releaseDate: '2020-06-19',
    genre: 'Action-Adventure',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'Animal Crossing: New Horizons',
    description: 'Animal Crossing: New Horizons is a life simulation game developed by Nintendo.',
    releaseDate: '2020-03-20',
    genre: 'Life Simulation',
    publisher: 'Nintendo',
  },
  {
    name: 'Among Us',
    description: 'Among Us is a multiplayer social deduction game developed by InnerSloth.',
    releaseDate: '2018-06-15',
    genre: 'Social Deduction',
    publisher: 'InnerSloth',
  },
  {
    name: 'Genshin Impact',
    description: 'Genshin Impact is an action RPG with an open-world fantasy setting.',
    releaseDate: '2020-09-28',
    genre: 'Action RPG',
    publisher: 'miHoYo',
  },
  {
    name: 'God of War (2018)',
    description: 'God of War is an action-adventure game that follows Kratos in a new setting.',
    releaseDate: '2018-04-20',
    genre: 'Action-Adventure',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'Call of Duty: Modern Warfare',
    description: 'Modern Warfare is a first-person shooter game developed by Infinity Ward.',
    releaseDate: '2019-10-25',
    genre: 'First-Person Shooter',
    publisher: 'Activision',
  },
  {
    name: 'Super Mario Odyssey',
    description: 'Super Mario Odyssey is a platformer game featuring Mario in an open world.',
    releaseDate: '2017-10-27',
    genre: 'Platformer',
    publisher: 'Nintendo',
  },
  {
    name: 'FIFA 22',
    description: 'FIFA 22 is a football simulation game developed and published by EA Sports.',
    releaseDate: '2021-10-01',
    genre: 'Sports',
    publisher: 'Electronic Arts',
  },
  {
    name: 'Persona 5',
    description: 'Persona 5 is a role-playing game set in modern-day Tokyo with supernatural elements.',
    releaseDate: '2016-09-15',
    genre: 'Role-Playing',
    publisher: 'Atlus',
  },
  {
    name: "Assassin's Creed Valhalla",
    description: "Assassin's Creed Valhalla is an action RPG set in the Viking age.",
    releaseDate: '2020-11-10',
    genre: 'Action RPG',
    publisher: 'Ubisoft',
  },
  {
    name: 'Overwatch',
    description: 'Overwatch is a team-based multiplayer first-person shooter developed by Blizzard Entertainment.',
    releaseDate: '2016-05-24',
    genre: 'First-Person Shooter',
    publisher: 'Blizzard Entertainment',
  },
  {
    name: 'Monster Hunter: World',
    description: 'Monster Hunter: World is an action RPG where players hunt and capture monsters in a fantasy world.',
    releaseDate: '2018-01-26',
    genre: 'Action RPG',
    publisher: 'Capcom',
  },
  {
    name: 'The Sims 4',
    description: 'The Sims 4 is a life simulation game where players create and control virtual people.',
    releaseDate: '2014-09-02',
    genre: 'Life Simulation',
    publisher: 'Electronic Arts',
  },
  {
    name: 'Fallout 4',
    description: 'Fallout 4 is an open-world action RPG set in a post-apocalyptic world.',
    releaseDate: '2015-11-10',
    genre: 'Action RPG',
    publisher: 'Bethesda Softworks',
  },
  {
    name: 'League of Legends',
    description: 'League of Legends is a multiplayer online battle arena (MOBA) game developed by Riot Games.',
    releaseDate: '2009-10-27',
    genre: 'MOBA',
    publisher: 'Riot Games',
  },
  {
    name: 'Death Stranding',
    description: 'Death Stranding is an action game developed by Kojima Productions.',
    releaseDate: '2019-11-08',
    genre: 'Action',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: "Tom Clancy's Rainbow Six Siege",
    description: 'Rainbow Six Siege is a tactical shooter game developed by Ubisoft.',
    releaseDate: '2015-12-01',
    genre: 'Tactical Shooter',
    publisher: 'Ubisoft',
  },
  {
    name: 'Horizon Zero Dawn',
    description: 'Horizon Zero Dawn is an action RPG set in a post-apocalyptic world where robotic creatures roam.',
    releaseDate: '2017-02-28',
    genre: 'Action RPG',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'Destiny 2',
    description: 'Destiny 2 is a multiplayer online shooter game with role-playing elements.',
    releaseDate: '2017-09-06',
    genre: 'First-Person Shooter',
    publisher: 'Bungie',
  },
  {
    name: 'Resident Evil Village',
    description: 'Resident Evil Village is a survival horror game developed by Capcom.',
    releaseDate: '2021-05-07',
    genre: 'Survival Horror',
    publisher: 'Capcom',
  },
  {
    name: 'Borderlands 3',
    description: 'Borderlands 3 is a looter shooter game set in a sci-fi world.',
    releaseDate: '2019-09-13',
    genre: 'Looter Shooter',
    publisher: '2K Games',
  },
  {
    name: 'Star Wars Jedi: Fallen Order',
    description: 'Jedi: Fallen Order is an action-adventure game set in the Star Wars universe.',
    releaseDate: '2019-11-15',
    genre: 'Action-Adventure',
    publisher: 'Electronic Arts',
  },
  {
    name: 'World of Warcraft',
    description:
      'World of Warcraft is a massively multiplayer online role-playing game (MMORPG) developed by Blizzard Entertainment.',
    releaseDate: '2004-11-23',
    genre: 'MMORPG',
    publisher: 'Blizzard Entertainment',
  },
  {
    name: 'Super Smash Bros. Ultimate',
    description: 'Super Smash Bros. Ultimate is a crossover fighting game featuring characters from various franchises.',
    releaseDate: '2018-12-07',
    genre: 'Fighting',
    publisher: 'Nintendo',
  },
  {
    name: 'DOOM Eternal',
    description: 'DOOM Eternal is a first-person shooter game where players battle demonic forces.',
    releaseDate: '2020-03-20',
    genre: 'First-Person Shooter',
    publisher: 'Bethesda Softworks',
  },
  {
    name: 'Nier: Automata',
    description: 'Nier: Automata is an action RPG developed by PlatinumGames.',
    releaseDate: '2017-02-23',
    genre: 'Action RPG',
    publisher: 'Square Enix',
  },
  {
    name: 'Final Fantasy VII Remake',
    description: 'Final Fantasy VII Remake is a reimagining of the classic RPG with modern graphics and gameplay.',
    releaseDate: '2020-04-10',
    genre: 'Role-Playing',
    publisher: 'Square Enix',
  },
  {
    name: "Marvel's Spider-Man: Miles Morales",
    description: 'Spider-Man: Miles Morales is an action-adventure game based on the Marvel Comics character Miles Morales.',
    releaseDate: '2020-11-12',
    genre: 'Action-Adventure',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'Stardew Valley',
    description: 'Stardew Valley is a farming simulation game developed by ConcernedApe.',
    releaseDate: '2016-02-26',
    genre: 'Farming Simulation',
    publisher: 'ConcernedApe',
  },
  {
    name: 'Sekiro: Shadows Die Twice',
    description: 'Sekiro: Shadows Die Twice is an action-adventure game with challenging combat mechanics.',
    releaseDate: '2019-03-22',
    genre: 'Action-Adventure',
    publisher: 'Activision',
  },
  {
    name: 'The Legend of Zelda: Breath of the Wild 2',
    description: 'Breath of the Wild 2 is the highly anticipated sequel to the original game.',

    genre: 'Action-Adventure',
    publisher: 'Nintendo',
  },
  {
    name: 'Halo Infinite',
    description: 'Halo Infinite is a first-person shooter game in the Halo series.',

    genre: 'First-Person Shooter',
    publisher: 'Xbox Game Studios',
  },
  {
    name: 'Pokémon Sword and Shield',
    description: 'Pokémon Sword and Shield are RPGs set in the Pokémon universe.',
    releaseDate: '2019-11-15',
    genre: 'Role-Playing',
    publisher: 'Nintendo',
  },
  {
    name: 'Ghost of Tsushima',
    description: 'Ghost of Tsushima is an action-adventure game set in feudal Japan.',
    releaseDate: '2020-07-17',
    genre: 'Action-Adventure',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'Apex Legends',
    description: 'Apex Legends is a free-to-play battle royale game developed by Respawn Entertainment.',
    releaseDate: '2019-02-04',
    genre: 'Battle Royale',
    publisher: 'Electronic Arts',
  },
  {
    name: 'Rainbow Six Extraction',
    description: 'Rainbow Six Extraction is a cooperative tactical shooter based on the Rainbow Six Siege universe.',
    releaseDate: '2022-01-20',
    genre: 'Tactical Shooter',
    publisher: 'Ubisoft',
  },
  {
    name: 'Valorant',
    description: 'Valorant is a free-to-play first-person shooter with tactical gameplay.',
    releaseDate: '2020-06-02',
    genre: 'First-Person Shooter',
    publisher: 'Riot Games',
  },
  {
    name: 'Ratchet & Clank: Rift Apart',
    description: 'Ratchet & Clank: Rift Apart is an action-adventure game developed by Insomniac Games.',
    releaseDate: '2021-06-11',
    genre: 'Action-Adventure',
    publisher: 'Sony Interactive Entertainment',
  },
  {
    name: 'The Outer Worlds',
    description: 'The Outer Worlds is an action RPG set in a retro-futuristic universe.',
    releaseDate: '2019-10-25',
    genre: 'Action RPG',
    publisher: 'Private Division',
  },
  {
    name: 'Mortal Kombat 11',
    description: 'Mortal Kombat 11 is a fighting game featuring iconic characters from the Mortal Kombat series.',
    releaseDate: '2019-04-23',
    genre: 'Fighting',
    publisher: 'Warner Bros. Interactive Entertainment',
  },
  {
    name: 'Starfield',
    description: 'Starfield is an upcoming space exploration game developed by Bethesda Game Studios.',

    genre: 'Space Exploration',
    publisher: 'Bethesda Softworks',
  },
  {
    name: 'Diablo IV',
    description: 'Diablo IV is an upcoming action RPG in the Diablo series.',
    genre: 'Action RPG',
    publisher: 'Blizzard Entertainment',
  },
  {
    name: 'Dying Light 2',
    description: 'Dying Light 2 is an upcoming open-world action RPG with parkour mechanics.',
    genre: 'Action RPG',
    publisher: 'Techland',
  },
  {
    name: 'Hogwarts Legacy',
    description:
      'Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books.',
    releaseDate: '2022-12-31',
    genre: 'Action',
    publisher: 'Warner Bros. Interactive Entertainment',
  },
];

(async () => {
  logger.info('seeding games .....');
  await Game.bulkCreate(games);
  logger.info(`${games.length} games seeded`);
  process.exit();
})();
